# Generated by Django 5.2.13 on 2026-04-27 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('specialty', models.CharField(blank=True, max_length=200)),
                ('tier', models.PositiveSmallIntegerField(default=3, help_text='1 = highest influence, 5 = lowest')),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='CANDIDATE', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal MSL notes')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kols', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kols', to='accounts.tenant')),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KOLPaperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_note', models.TextField(blank=True)),
                ('is_author', models.BooleanField(default=False)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('kol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_links', to='kol.kol')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kol_links', to='literature.paper')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kol',
            index=models.Index(fields=['tenant', 'status'], name='kol_kol_tenant__0534e7_idx'),
        ),
        migrations.AddIndex(
            model_name='kol',
            index=models.Index(fields=['tenant', 'tier'], name='kol_kol_tenant__5dd8ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kolpaperlink',
            unique_together={('kol', 'paper')},
        ),
    ]
