# Generated by Django 5.2.13 on 2026-04-28 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('kol', '0001_initial'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KOLCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('institution', models.CharField(blank=True, max_length=300)),
                ('specialty', models.CharField(blank=True, max_length=200)),
                ('tier', models.PositiveSmallIntegerField(default=3)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('relevance_note', models.TextField(blank=True)),
                ('is_author', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Checking…'), ('LIKELY_CURRENT', 'Likely Current'), ('UNCERTAIN', 'Uncertain'), ('POSSIBLY_INACTIVE', 'Possibly Inactive')], default='UNVERIFIED', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('verification_concerns', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_candidates', to='kol.kol')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kol_candidates', to='literature.paper')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kol_candidates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kol_candidates', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='kol_kolcand_tenant__940d20_idx'), models.Index(fields=['tenant', 'paper'], name='kol_kolcand_tenant__a993e5_idx')],
            },
        ),
    ]
