# Generated by Django 5.2.13 on 2026-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0003_kolcandidate_nullable_paper_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolcandidate',
            name='search_query',
            field=models.CharField(blank=True, help_text='Keyword query used to discover this candidate (blank for paper-extracted ones).', max_length=400),
        ),
    ]
