# Generated by Django 5.2.13 on 2026-04-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI Draft'), ('CONFIRMED', 'Confirmed')], default='AI_DRAFT', max_length=20)),
                ('methodology', models.TextField(blank=True)),
                ('executive_paragraph', models.TextField(blank=True)),
                ('safety_summary', models.TextField(blank=True)),
                ('adverse_events', models.JSONField(default=list, help_text='[{event, incidence, page_ref}, ...]')),
                ('limitations', models.JSONField(default=list, help_text='[{limitation, page_ref}, ...]')),
                ('ai_prefilled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_summaries', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='literature.paper')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_summaries', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'paper summaries',
            },
        ),
        migrations.CreateModel(
            name='FindingsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Safety', 'Safety'), ('Other', 'Other')], default='Primary', max_length=20)),
                ('finding', models.TextField()),
                ('quantitative_result', models.CharField(blank=True, max_length=300)),
                ('page_ref', models.CharField(blank=True, max_length=100)),
                ('clinical_significance', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='summaries.papersummary')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='papersummary',
            index=models.Index(fields=['tenant', 'status'], name='summaries_p_tenant__77ae9a_idx'),
        ),
    ]
