# Generated by Django 5.2.13 on 2026-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEDICAL_LEAD', 'Medical Lead'), ('MEDICAL_AFFAIRS', 'Medical Affairs'), ('COMMERCIAL', 'Commercial'), ('ADMIN', 'Admin')], default='MEDICAL_AFFAIRS', max_length=20),
        ),
    ]
