# Generated by Django 5.2.13 on 2026-04-27 06:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('query', models.TextField()),
                ('filters', models.JSONField(default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='accounts.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('journal', models.CharField(max_length=300)),
                ('journal_short', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('issue', models.CharField(blank=True, max_length=20)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('pubmed_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pmcid', models.CharField(blank=True, max_length=20)),
                ('study_type', models.CharField(blank=True, choices=[('RCT', 'RCT'), ('Meta-analysis', 'Meta-analysis'), ('Systematic review', 'Systematic Review'), ('Observational', 'Observational'), ('Other', 'Other')], max_length=20)),
                ('source', models.CharField(choices=[('PUBMED_OA', 'PubMed Open Access'), ('PDF_UPLOAD', 'PDF Upload'), ('MANUAL', 'Manual Entry')], default='PUBMED_OA', max_length=20)),
                ('status', models.CharField(choices=[('AWAITING_UPLOAD', 'Awaiting Upload'), ('INGESTED', 'Ingested'), ('ASSESSED', 'Assessed'), ('SUMMARISED', 'Summarised'), ('CLAIMS_GENERATED', 'Claims Generated'), ('APPROVED', 'Approved')], default='INGESTED', max_length=20)),
                ('grade_rating', models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=10)),
                ('source_file', models.FileField(blank=True, upload_to='papers/')),
                ('full_text', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='literature__tenant__cc4e20_idx'), models.Index(fields=['tenant', 'published_date'], name='literature__tenant__48df48_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='paper_search_vector_idx')],
            },
        ),
    ]
