# Generated by Django 5.2.13 on 2026-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_savedsearch_funnel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doi_source',
            field=models.CharField(choices=[('PUBMED', 'PubMed'), ('CROSSREF', 'CrossRef'), ('USER_ENTRY', 'User Entry'), ('PDF_METADATA', 'PDF Metadata'), ('UNSET', 'Not Set')], default='UNSET', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='doi_verification_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='doi_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='doi_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
