# Generated by Django 5.2.13 on 2026-04-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI Draft'), ('CONFIRMED', 'Confirmed')], default='AI_DRAFT', max_length=20)),
                ('overall_rating', models.CharField(blank=True, choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=20)),
                ('rob_rating', models.CharField(blank=True, choices=[('Not serious', 'Not serious'), ('Serious', 'Serious'), ('Very serious', 'Very serious'), ('Undetected', 'Undetected'), ('Suspected', 'Suspected'), ('No information', 'No information')], max_length=20)),
                ('rob_rationale', models.TextField(blank=True)),
                ('rob_page_ref', models.CharField(blank=True, max_length=100)),
                ('inconsistency_rating', models.CharField(blank=True, choices=[('Not serious', 'Not serious'), ('Serious', 'Serious'), ('Very serious', 'Very serious'), ('Undetected', 'Undetected'), ('Suspected', 'Suspected'), ('No information', 'No information')], max_length=20)),
                ('inconsistency_rationale', models.TextField(blank=True)),
                ('inconsistency_page_ref', models.CharField(blank=True, max_length=100)),
                ('indirectness_rating', models.CharField(blank=True, choices=[('Not serious', 'Not serious'), ('Serious', 'Serious'), ('Very serious', 'Very serious'), ('Undetected', 'Undetected'), ('Suspected', 'Suspected'), ('No information', 'No information')], max_length=20)),
                ('indirectness_rationale', models.TextField(blank=True)),
                ('indirectness_page_ref', models.CharField(blank=True, max_length=100)),
                ('imprecision_rating', models.CharField(blank=True, choices=[('Not serious', 'Not serious'), ('Serious', 'Serious'), ('Very serious', 'Very serious'), ('Undetected', 'Undetected'), ('Suspected', 'Suspected'), ('No information', 'No information')], max_length=20)),
                ('imprecision_rationale', models.TextField(blank=True)),
                ('imprecision_page_ref', models.CharField(blank=True, max_length=100)),
                ('publication_bias_rating', models.CharField(blank=True, choices=[('Not serious', 'Not serious'), ('Serious', 'Serious'), ('Very serious', 'Very serious'), ('Undetected', 'Undetected'), ('Suspected', 'Suspected'), ('No information', 'No information')], max_length=20)),
                ('publication_bias_rationale', models.TextField(blank=True)),
                ('publication_bias_page_ref', models.CharField(blank=True, max_length=100)),
                ('ai_prefilled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_grade_assessments', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessment', to='literature.paper')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assessments', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='assessment__tenant__a9e660_idx')],
            },
        ),
        migrations.CreateModel(
            name='RobAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI Draft'), ('CONFIRMED', 'Confirmed')], default='AI_DRAFT', max_length=20)),
                ('overall_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d1_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d1_rationale', models.TextField(blank=True)),
                ('d1_page_ref', models.CharField(blank=True, max_length=100)),
                ('d2_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d2_rationale', models.TextField(blank=True)),
                ('d2_page_ref', models.CharField(blank=True, max_length=100)),
                ('d3_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d3_rationale', models.TextField(blank=True)),
                ('d3_page_ref', models.CharField(blank=True, max_length=100)),
                ('d4_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d4_rationale', models.TextField(blank=True)),
                ('d4_page_ref', models.CharField(blank=True, max_length=100)),
                ('d5_judgment', models.CharField(blank=True, choices=[('Low', 'Low'), ('Some concerns', 'Some concerns'), ('High', 'High'), ('No information', 'No information')], max_length=20)),
                ('d5_rationale', models.TextField(blank=True)),
                ('d5_page_ref', models.CharField(blank=True, max_length=100)),
                ('ai_prefilled', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_rob_assessments', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rob_assessment', to='literature.paper')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rob_assessments', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='assessment__tenant__1dea5c_idx')],
            },
        ),
    ]
