# Generated by Django 5.2.13 on 2026-04-30 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_compliance_fields'),
        ('engagement', '0001_initial'),
        ('kol', '0004_alter_kolcandidate_search_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('agenda_items', models.JSONField(default=list, help_text='List of agenda item strings')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advisory_boards', to=settings.AUTH_USER_MODEL)),
                ('kols', models.ManyToManyField(blank=True, related_name='advisory_boards', to='kol.kol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_boards', to='accounts.tenant')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(blank=True, help_text='e.g. Webinar, Workshop, Symposium', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_events', to='accounts.tenant')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
