# Generated by Django 5.2.13 on 2026-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_advisoryboard_otherevent'),
        ('kol', '0004_alter_kolcandidate_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherevent',
            name='kols',
            field=models.ManyToManyField(blank=True, related_name='other_events', to='kol.kol'),
        ),
    ]
