# Generated by Django 5.2.13 on 2026-04-27 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('SERIOUS', 'Serious'), ('MODERATE', 'Moderate'), ('MILD', 'Mild')], default='MODERATE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MONITORING', 'Monitoring'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prepared_response', models.TextField(blank=True, help_text='MSL-ready talking point for this signal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_signals', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence_treatment', models.CharField(blank=True, max_length=100)),
                ('incidence_control', models.CharField(blank=True, max_length=100)),
                ('passage', models.TextField(blank=True)),
                ('page_ref', models.CharField(blank=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_mentions', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_mentions', to='literature.paper')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='safety.safetysignal')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safetysignal',
            index=models.Index(fields=['tenant', 'status'], name='safety_safe_tenant__19fc07_idx'),
        ),
        migrations.AddIndex(
            model_name='safetysignal',
            index=models.Index(fields=['tenant', 'severity'], name='safety_safe_tenant__911946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signalmention',
            unique_together={('signal', 'paper')},
        ),
    ]
