# Generated by Django 5.2.13 on 2026-04-28 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question', models.TextField()),
                ('source', models.CharField(choices=[('HCP', 'Healthcare Professional'), ('PATIENT', 'Patient / Carer'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], default='HCP', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DRAFT', 'Draft Response'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('citations', models.JSONField(default=list, help_text='[{paper_id, apa7, page_ref}, ...]')),
                ('keywords', models.JSONField(default=list, help_text='AI-extracted keywords for trend analysis')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_enquiries', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_enquiries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='accounts.tenant')),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='medinfo_enq_tenant__36fa58_idx')],
            },
        ),
    ]
