# Generated by Django 5.2.13 on 2026-04-27 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('literature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_text', models.TextField()),
                ('endpoint_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], default='PRIMARY', max_length=20)),
                ('source_passage', models.TextField(blank=True)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('fair_balance', models.TextField(blank=True)),
                ('fair_balance_reference', models.CharField(blank=True, max_length=200)),
                ('fidelity_checklist', models.JSONField(default=dict, help_text='Keys: verbatim_data (bool), population_match (bool), endpoint_match (bool), no_extrapolation (bool), fair_balance_present (bool)')),
                ('status', models.CharField(choices=[('AI_DRAFT', 'AI Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='AI_DRAFT', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('veeva_mat_id', models.CharField(blank=True, max_length=30)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='literature.paper')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.tenant')),
            ],
            options={
                'ordering': ['endpoint_type', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='claims_core_tenant__876b48_idx'), models.Index(fields=['tenant', 'paper'], name='claims_core_tenant__a8ac5c_idx')],
            },
        ),
    ]
