# Generated by Django 5.2.13 on 2026-04-29 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coreclaim',
            name='approved_indication',
            field=models.CharField(blank=True, help_text='TGA-approved indication this claim relates to. Must not exceed the approved indication.', max_length=500),
        ),
        migrations.AddField(
            model_name='coreclaim',
            name='certified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreclaim',
            name='certified_by',
            field=models.ForeignKey(blank=True, help_text='Medical Lead (MD/PharmD) who certified this claim per MA Code §8.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coreclaim',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Date by which this claim must be reviewed for continued accuracy. MA Code requires periodic review.', null=True),
        ),
        migrations.AddField(
            model_name='coreclaim',
            name='pi_version',
            field=models.CharField(blank=True, help_text="Product Information version/date this claim was verified against (e.g. 'v1.4 — March 2026').", max_length=100),
        ),
        migrations.AlterField(
            model_name='coreclaim',
            name='fidelity_checklist',
            field=models.JSONField(default=dict, help_text='Keys: verbatim_data (bool), population_match (bool), endpoint_match (bool), no_extrapolation (bool), fair_balance_present (bool), approved_indication_only (bool). approved_indication_only: claim falls within the TGA-approved indication (MA Code req.).'),
        ),
    ]
