# Generated by Django 5.2.13 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('DELETE', 'Delete'), ('AI_DRAFT', 'Ai Draft'), ('INGEST', 'Ingest')], max_length=20),
        ),
    ]
